version: '3'
services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: curso
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - pg_data:/var/lib/postgresql/data

  fastapi-app:
    build:
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres

volumes:
  pg_data:
