version: '3'
services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - app/.env
    volumes:
      - pg_data:/var/lib/postgresql/data

  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - app/.env

volumes:
  pg_data:
